import type { SubjectConfig } from "../subjectKit";

export const chemData: Omit<SubjectConfig, "rootClass" | "accent"> = {
  heroTitle: { zh: "万物化学", en: "Chemistry of Everything" },
  heroSub: { zh: "物质之变", en: "The Transformations of Matter" },
  intro: {
    zh: "从原子结构、元素周期表、常见实验方程式到材料与化学家，按高中化学脉络系统梳理核心知识。",
    en: "Atomic structure, the periodic table, common lab equations, materials and chemists — core high-school chemistry organized coherently.",
  },
  modules: [
    /* ===================== 核心概念 ===================== */
    {
      key: "concepts",
      icon: "🧪",
      title: { zh: "核心概念", en: "Core Concepts" },
      items: [
        {
          id: "atom",
          icon: "⚛️",
          term: { zh: "原子结构", en: "Atomic Structure" },
          level: 1,
          oneLiner: { zh: "原子由带正电的原子核与核外电子组成，电子排布决定化学性质。", en: "Atoms have a positive nucleus and orbiting electrons; electron arrangement decides chemistry." },
          detail: { zh: "原子核含质子与中子；电子按能级与轨道分层排布，价电子参与成键。", en: "The nucleus holds protons and neutrons; electrons occupy shells; valence electrons form bonds." },
          tags: [{ zh: "结构", en: "Structure" }],
        },
        {
          id: "periodic-law",
          icon: "📐",
          term: { zh: "元素周期律", en: "Periodic Law" },
          level: 1,
          oneLiner: { zh: "元素性质随原子序数呈周期性变化，周期表是其系统呈现。", en: "Element properties repeat periodically with atomic number; the table expresses this." },
          detail: { zh: "门捷列夫按原子量排列并预言未知元素；现代周期表按原子序数排列。", en: "Mendeleev arranged by atomic weight; the modern table uses atomic number." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "bond",
          icon: "🔗",
          term: { zh: "化学键", en: "Chemical Bonds" },
          level: 1,
          oneLiner: { zh: "原子通过离子键、共价键或金属键结合成分子与晶体。", en: "Atoms join via ionic, covalent or metallic bonds." },
          detail: { zh: "离子键靠电子转移、共价键靠电子共享、金属键靠离域电子海，决定硬度、熔沸点和导电性。", en: "Ionic (transfer), covalent (sharing) and metallic (delocalized) bonds set hardness, melting point and conductivity." },
          tags: [{ zh: "成键", en: "Bonding" }],
        },
        {
          id: "acid-base",
          icon: "🧫",
          term: { zh: "酸碱", en: "Acids & Bases" },
          level: 2,
          oneLiner: { zh: "酸给出质子（H⁺），碱接受质子；pH 衡量溶液酸碱性。", en: "Acids donate protons (H⁺), bases accept them; pH measures acidity." },
          detail: { zh: "按布朗斯特-劳里定义，酸碱是质子授受关系；强酸强碱中和生成盐与水。", en: "Brønsted–Lowry defines them by proton transfer; neutralization yields salt and water." },
          tags: [{ zh: "酸碱", en: "Acid-Base" }],
        },
        {
          id: "redox",
          icon: "🔋",
          term: { zh: "氧化还原反应", en: "Redox" },
          level: 2,
          oneLiner: { zh: "电子转移过程：升价被氧化，降价被还原。", en: "Electron transfer: oxidation raises oxidation state, reduction lowers it." },
          detail: { zh: "燃烧、腐蚀、电池都属氧化还原；氧化剂得电子、还原剂失电子，二者相伴。", en: "Combustion, corrosion and batteries are redox; oxidizing and reducing agents act together." },
          tags: [{ zh: "反应", en: "Reactions" }],
        },
        {
          id: "equilibrium",
          icon: "⚖️",
          term: { zh: "化学平衡", en: "Chemical Equilibrium" },
          level: 2,
          oneLiner: { zh: "可逆反应正逆速率相等时，各物质浓度不再变化。", en: "When forward and reverse rates equal, concentrations stop changing." },
          detail: { zh: "勒夏特列原理：改变浓度、温度或压强，平衡向削弱该改变的方向移动。", en: "Le Chatelier's principle: a system shifts to counteract changes in concentration, temperature or pressure." },
          tags: [{ zh: "平衡", en: "Equilibrium" }],
        },
        {
          id: "rate",
          icon: "⏱️",
          term: { zh: "反应速率", en: "Reaction Rate" },
          level: 2,
          oneLiner: { zh: "浓度、温度、催化剂与表面积都会影响反应快慢。", en: "Concentration, temperature, catalysts and surface area affect rate." },
          detail: { zh: "升温或加催化剂可降低活化能、加快反应；碰撞理论解释有效碰撞。", en: "Higher temperature or catalysts lower activation energy; collision theory explains effective collisions." },
          tags: [{ zh: "动力学", en: "Kinetics" }],
        },
        {
          id: "thermo",
          icon: "🌡️",
          term: { zh: "化学热力学", en: "Chemical Thermodynamics" },
          level: 3,
          oneLiner: { zh: "用焓、熵、吉布斯自由能判断反应能否自发。", en: "Enthalpy, entropy and Gibbs free energy decide spontaneity." },
          detail: { zh: "ΔG=ΔH−TΔS；ΔG<0 时反应自发，放热与熵增都有利于自发。", en: "ΔG=ΔH−TΔS; ΔG<0 means spontaneous." },
          tags: [{ zh: "热力学", en: "Thermodynamics" }],
        },
        {
          id: "coordination",
          icon: "🌀",
          term: { zh: "配位化合物", en: "Coordination Compounds" },
          level: 3,
          oneLiner: { zh: "中心金属离子与配体通过配位键形成的复杂结构。", en: "Central metal ions bonded to ligands via coordinate bonds." },
          detail: { zh: "常见于催化剂、颜料与生物分子（如血红素中的铁）。", en: "Seen in catalysts, pigments and biomolecules (e.g. iron in heme)." },
          tags: [{ zh: "无机", en: "Inorganic" }],
        },
        {
          id: "solution",
          icon: "💧",
          term: { zh: "溶液与溶解度", en: "Solutions & Solubility" },
          level: 1,
          oneLiner: { zh: "一种或多种物质分散到另一种物质中形成均一稳定的混合物。", en: "A homogeneous, stable mixture of solutes dispersed in a solvent." },
          detail: { zh: "溶解度随温度升高一般增大（气体反之）；饱和溶液与温度、压强有关。", en: "Solubility usually rises with temperature (gases opposite); saturation depends on T and pressure." },
          tags: [{ zh: "溶液", en: "Solutions" }],
        },
        {
          id: "organic-basics",
          icon: "🔗",
          term: { zh: "有机化学基础", en: "Organic Basics" },
          level: 2,
          oneLiner: { zh: "以碳为骨架的化合物，常见官能团有羟基、羧基、氨基等。", en: "Carbon-based compounds with functional groups like hydroxyl, carboxyl and amino." },
          detail: { zh: "烷、烯、炔、醇、酸、酯等构成有机家族；同分异构现象普遍。", en: "Alkanes, alkenes, alcohols, acids and esters form the organic family; isomers are common." },
          tags: [{ zh: "有机", en: "Organic" }],
        },
      ],
    },
    /* ===================== 元素周期表 ===================== */
    {
      key: "periodic-table",
      icon: "📊",
      title: { zh: "元素周期表", en: "Periodic Table" },
      items: [
        {
          id: "periods-groups",
          icon: "🟰",
          term: { zh: "周期与族", en: "Periods & Groups" },
          level: 1,
          oneLiner: { zh: "横排为周期（电子层数相同），纵列为族（最外层电子数相同）。", en: "Rows are periods (same shells); columns are groups (same valence electrons)." },
          detail: { zh: "现有 7 个周期、18 个纵列；主族（IA–VIIA）与副族（过渡金属）性质各异。", en: "Seven periods and 18 columns; main groups and transition metals differ in behavior." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "same-period",
          icon: "➡️",
          term: { zh: "同周期递变规律", en: "Across a Period" },
          level: 2,
          oneLiner: { zh: "从左到右原子半径减小、金属性减弱、非金属性增强。", en: "Left to right: radius shrinks, metallic character weakens, nonmetals strengthen." },
          detail: { zh: "核电荷数增大使原子对电子吸引更强，故失电子能力减弱、得电子能力增强。", en: "Rising nuclear charge tightens the pull on electrons, weakening loss and easing gain." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "same-group",
          icon: "⬇️",
          term: { zh: "同主族递变规律", en: "Down a Group" },
          level: 2,
          oneLiner: { zh: "从上到下原子半径增大、金属性增强、非金属性减弱。", en: "Top to bottom: radius grows, metallic character strengthens, nonmetals weaken." },
          detail: { zh: "电子层数增多使外层电子离核更远，更易失去。", en: "Extra shells move valence electrons farther, easing their loss." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "metal-nonmetal",
          icon: "⚔️",
          term: { zh: "金属性与非金属性", en: "Metallic & Nonmetallic" },
          level: 1,
          oneLiner: { zh: "金属性指失电子能力，非金属性指得电子能力；分界线附近为类金属。", en: "Metallic = losing electrons; nonmetallic = gaining; metalloids sit near the divide." },
          detail: { zh: "左下角（如铯、钫）金属性最强，右上角（如氟）非金属性最强。", en: "Strongest metals bottom-left (Cs, Fr); strongest nonmetal top-right (F)." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "atomic-radius",
          icon: "⭕",
          term: { zh: "原子半径趋势", en: "Atomic Radius Trend" },
          level: 2,
          oneLiner: { zh: "同周期减小、同主族增大；稀有气体因计量方式通常单独较大。", en: "Shrinks across a period, grows down a group; noble-gas values differ by convention." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "electronegativity",
          icon: "🎚️",
          term: { zh: "电负性与电离能", en: "Electronegativity & Ionization" },
          level: 2,
          oneLiner: { zh: "电负性衡量吸引共用电子能力（氟最大）；电离能是失电子所需能量。", en: "Electronegativity gauges electron attraction (F largest); ionization energy is to remove an electron." },
          detail: { zh: "二者同周期递增、同主族递减；稀有气体电离能出现反常。", en: "Both rise across a period and fall down a group; noble gases are exceptions." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "transition",
          icon: "🔩",
          term: { zh: "过渡元素", en: "Transition Elements" },
          level: 2,
          oneLiner: { zh: "周期表中部 d 区元素，多为有色、可变价、易形成配合物。", en: "Central d-block elements: often colored, multiple valences, complex-forming." },
          detail: { zh: "铁、铜、锌等是生命与工业的重要过渡金属。", en: "Fe, Cu, Zn are vital transition metals in life and industry." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
        {
          id: "noble-gas",
          icon: "🎈",
          term: { zh: "稀有气体", en: "Noble Gases" },
          level: 1,
          oneLiner: { zh: "最外层电子已满，化学性质极稳定，过去称惰性气体。", en: "Filled outer shells make them extremely stable, once called inert gases." },
          detail: { zh: "氦、氖、氩、氪、氙、氡；可用于保护气、照明与制冷。", en: "He, Ne, Ar, Kr, Xe, Rn; used as shielding gas, lighting and cooling." },
          tags: [{ zh: "周期表", en: "Periodic" }],
        },
      ],
    },
    /* ===================== 元素 ===================== */
    {
      key: "elements",
      icon: "🧬",
      title: { zh: "元素", en: "Elements" },
      items: [
        { id: "h", icon: "💧", term: { zh: "氢", en: "Hydrogen" }, value: { zh: "H · 1 号", en: "H · Z=1" }, oneLiner: { zh: "宇宙中最丰富的元素，最轻的气体，可作清洁能源。", en: "Most abundant element; lightest gas and clean energy carrier." } },
        { id: "he", icon: "🎈", term: { zh: "氦", en: "Helium" }, value: { zh: "He · 2 号", en: "He · Z=2" }, oneLiner: { zh: "稀有气体，极稳定、密度小，用于气球与制冷。", en: "Noble gas, very stable and light; used in balloons and cooling." } },
        { id: "li", icon: "🔋", term: { zh: "锂", en: "Lithium" }, value: { zh: "Li · 3 号", en: "Li · Z=3" }, oneLiner: { zh: "最轻的金属，现代电池的核心材料。", en: "Lightest metal; core material of modern batteries." } },
        { id: "c", icon: "⚫", term: { zh: "碳", en: "Carbon" }, value: { zh: "C · 6 号", en: "C · Z=6" }, oneLiner: { zh: "有机化学的核心，能形成长链与多种同素异形体。", en: "Core of organic chemistry; forms chains and allotropes like graphite and diamond." } },
        { id: "n", icon: "💨", term: { zh: "氮", en: "Nitrogen" }, value: { zh: "N · 7 号", en: "N · Z=7" }, oneLiner: { zh: "空气中含量最高的气体，是蛋白质与核酸的组成元素。", en: "Most abundant gas in air; part of proteins and nucleic acids." } },
        { id: "o", icon: "🫧", term: { zh: "氧", en: "Oxygen" }, value: { zh: "O · 8 号", en: "O · Z=8" }, oneLiner: { zh: "维持呼吸与燃烧，地壳中含量最高的元素。", en: "Sustains respiration and combustion; most abundant in Earth's crust." } },
        { id: "na", icon: "🧂", term: { zh: "钠", en: "Sodium" }, value: { zh: "Na · 11 号", en: "Na · Z=11" }, oneLiner: { zh: "活泼碱金属，与氯结合成食盐（NaCl）。", en: "Reactive alkali metal; pairs with chlorine as table salt (NaCl)." } },
        { id: "mg", icon: "🌟", term: { zh: "镁", en: "Magnesium" }, value: { zh: "Mg · 12 号", en: "Mg · Z=12" }, oneLiner: { zh: "轻金属，燃烧发出耀眼白光，是叶绿素的中心原子。", en: "Light metal burning with bright white light; center of chlorophyll." } },
        { id: "al", icon: "🥫", term: { zh: "铝", en: "Aluminum" }, value: { zh: "Al · 13 号", en: "Al · Z=13" }, oneLiner: { zh: "地壳含量最高的金属，质轻耐腐蚀。", en: "Most abundant crustal metal; light and corrosion-resistant." } },
        { id: "si", icon: "💾", term: { zh: "硅", en: "Silicon" }, value: { zh: "Si · 14 号", en: "Si · Z=14" }, oneLiner: { zh: "半导体工业的基础，地壳第二丰富的元素。", en: "Basis of semiconductors; second-most abundant crustal element." } },
        { id: "p", icon: "🔥", term: { zh: "磷", en: "Phosphorus" }, value: { zh: "P · 15 号", en: "P · Z=15" }, oneLiner: { zh: "生命必需元素，存在于 ATP 与 DNA 中。", en: "Essential to life, in ATP and DNA." } },
        { id: "s", icon: "🥚", term: { zh: "硫", en: "Sulfur" }, value: { zh: "S · 16 号", en: "S · Z=16" }, oneLiner: { zh: "黄色固体，用于硫酸生产与火药。", en: "Yellow solid; used in sulfuric acid and gunpowder." } },
        { id: "cl", icon: "🟢", term: { zh: "氯", en: "Chlorine" }, value: { zh: "Cl · 17 号", en: "Cl · Z=17" }, oneLiner: { zh: "黄绿色气体，强氧化性与杀菌消毒能力。", en: "Yellow-green gas; strong oxidizer used in disinfection." } },
        { id: "k", icon: "🍌", term: { zh: "钾", en: "Potassium" }, value: { zh: "K · 19 号", en: "K · Z=19" }, oneLiner: { zh: "活泼碱金属，对神经与肌肉功能至关重要。", en: "Reactive alkali metal vital to nerve and muscle function." } },
        { id: "ca", icon: "🦴", term: { zh: "钙", en: "Calcium" }, value: { zh: "Ca · 20 号", en: "Ca · Z=20" }, oneLiner: { zh: "骨骼与牙齿的主要成分，常见于石灰石与石膏。", en: "Main component of bone and teeth; in limestone and gypsum." } },
        { id: "fe", icon: "🔩", term: { zh: "铁", en: "Iron" }, value: { zh: "Fe · 26 号", en: "Fe · Z=26" }, oneLiner: { zh: "人类文明的支柱金属，血红蛋白与钢的核心成分。", en: "Backbone metal of civilization; core of hemoglobin and steel." } },
        { id: "cu", icon: "🟤", term: { zh: "铜", en: "Copper" }, value: { zh: "Cu · 29 号", en: "Cu · Z=29" }, oneLiner: { zh: "优良导体，古代即用于铸造与货币。", en: "Excellent conductor; used since antiquity for casting and coinage." } },
        { id: "zn", icon: "⚙️", term: { zh: "锌", en: "Zinc" }, value: { zh: "Zn · 30 号", en: "Zn · Z=30" }, oneLiner: { zh: "常作镀锌防锈层，也是干电池负极材料。", en: "Used for galvanizing and as battery anodes." } },
        { id: "ag", icon: "🥈", term: { zh: "银", en: "Silver" }, value: { zh: "Ag · 47 号", en: "Ag · Z=47" }, oneLiner: { zh: "导电导热最佳的金属，用于首饰与电子。", en: "Best conductor; used in jewelry and electronics." } },
        { id: "au", icon: "🥇", term: { zh: "金", en: "Gold" }, value: { zh: "Au · 79 号", en: "Au · Z=79" }, oneLiner: { zh: "化学性质极稳定、延展性好的贵金属，自古作货币与饰品。", en: "Extremely stable and ductile noble metal, long used for coinage." } },
      ],
    },
    /* ===================== 反应类型 ===================== */
    {
      key: "reactions",
      icon: "🔥",
      title: { zh: "反应类型", en: "Reaction Types" },
      items: [
        { id: "synthesis", icon: "➕", term: { zh: "化合反应", en: "Synthesis" }, oneLiner: { zh: "多种物质生成一种新物质（A + B → AB）。", en: "Several substances form one product (A + B → AB)." } },
        { id: "decomposition", icon: "➖", term: { zh: "分解反应", en: "Decomposition" }, oneLiner: { zh: "一种物质分解成多种物质（AB → A + B）。", en: "One substance breaks into several (AB → A + B)." } },
        { id: "single", icon: "🔁", term: { zh: "置换反应", en: "Single Replacement" }, oneLiner: { zh: "活泼金属把较不活泼金属从其盐中置换出来。", en: "A more active metal displaces a less active one from its salt." } },
        { id: "double", icon: "🔄", term: { zh: "复分解反应", en: "Double Replacement" }, oneLiner: { zh: "两种化合物交换组分，常生成沉淀、气体或水。", en: "Two compounds exchange parts, often yielding precipitate, gas or water." } },
        { id: "combustion", icon: "🔥", term: { zh: "燃烧", en: "Combustion" }, oneLiner: { zh: "物质与氧气的剧烈氧化，发光放热。", en: "Vigorous oxidation with oxygen, releasing light and heat." } },
        { id: "neutralization", icon: "🧪", term: { zh: "中和反应", en: "Neutralization" }, oneLiner: { zh: "酸与碱反应生成盐和水，pH 趋近 7。", en: "Acid and base form salt and water, pH trending to 7." } },
      ],
    },
    /* ===================== 实验方程式 ===================== */
    {
      key: "equations",
      icon: "📝",
      title: { zh: "常见实验方程式", en: "Common Lab Equations" },
      items: [
        {
          id: "eq-h2o2",
          icon: "🧪",
          term: { zh: "过氧化氢分解制氧气", en: "Oxygen from H₂O₂" },
          oneLiner: { zh: "2H₂O₂ ==[MnO₂]== 2H₂O + O₂↑", en: "2H₂O₂ ==[MnO₂]== 2H₂O + O₂↑" },
          detail: { zh: "二氧化锰作催化剂，实验室常温制氧的常用方法。", en: "MnO₂ catalyzes this common room-temperature lab method for O₂." },
          tags: [{ zh: "制气", en: "Gas" }],
        },
        {
          id: "eq-kmno4",
          icon: "🟣",
          term: { zh: "高锰酸钾受热分解", en: "KMnO₄ Decomposition" },
          oneLiner: { zh: "2KMnO₄ ==△== K₂MnO₄ + MnO₂ + O₂↑", en: "2KMnO₄ ==△== K₂MnO₄ + MnO₂ + O₂↑" },
          detail: { zh: "加热即可制氧，无需催化剂。", en: "Heating alone yields oxygen, no catalyst needed." },
          tags: [{ zh: "制气", en: "Gas" }],
        },
        {
          id: "eq-kclo3",
          icon: "🟡",
          term: { zh: "氯酸钾受热分解", en: "KClO₃ Decomposition" },
          oneLiner: { zh: "2KClO₃ ==[MnO₂, △]== 2KCl + 3O₂↑", en: "2KClO₃ ==[MnO₂, △]== 2KCl + 3O₂↑" },
          tags: [{ zh: "制气", en: "Gas" }],
        },
        {
          id: "eq-co2",
          icon: "🪨",
          term: { zh: "大理石与盐酸制二氧化碳", en: "CO₂ from Carbonate" },
          oneLiner: { zh: "CaCO₃ + 2HCl = CaCl₂ + H₂O + CO₂↑", en: "CaCO₃ + 2HCl = CaCl₂ + H₂O + CO₂↑" },
          detail: { zh: "实验室制 CO₂ 的首选反应，也可用稀硫酸代替盐酸观察差异。", en: "The standard lab route to CO₂." },
          tags: [{ zh: "制气", en: "Gas" }],
        },
        {
          id: "eq-electrolysis",
          icon: "⚡",
          term: { zh: "电解水", en: "Electrolysis of Water" },
          oneLiner: { zh: "2H₂O ==通电== 2H₂↑ + O₂↑", en: "2H₂O ==通电== 2H₂↑ + O₂↑" },
          detail: { zh: "加少量电解质增强导电性；体积比 V(H₂):V(O₂)=2:1。", en: "A little electrolyte aids conduction; volume ratio H₂:O₂ = 2:1." },
          tags: [{ zh: "电解", en: "Electrolysis" }],
        },
        {
          id: "eq-fe-cuso4",
          icon: "🔵",
          term: { zh: "铁置换硫酸铜（湿法炼铜）", en: "Fe Displaces Cu" },
          oneLiner: { zh: "Fe + CuSO₄ = FeSO₄ + Cu", en: "Fe + CuSO₄ = FeSO₄ + Cu" },
          detail: { zh: "活泼金属置换不活泼金属，溶液由蓝变浅绿。", en: "A more active metal displaces a less active one; blue fades to pale green." },
          tags: [{ zh: "置换", en: "Displacement" }],
        },
        {
          id: "eq-metal-acid",
          icon: "🔩",
          term: { zh: "活泼金属与稀硫酸", en: "Metal + Acid" },
          oneLiner: { zh: "Zn + H₂SO₄ = ZnSO₄ + H₂↑", en: "Zn + H₂SO₄ = ZnSO₄ + H₂↑" },
          detail: { zh: "镁、锌、铁可与稀酸反应放氢，铜等不活泼金属不行。", en: "Mg, Zn, Fe release H₂ with dilute acid; Cu does not." },
          tags: [{ zh: "置换", en: "Displacement" }],
        },
        {
          id: "eq-ch4",
          icon: "🔥",
          term: { zh: "甲烷燃烧", en: "Methane Combustion" },
          oneLiner: { zh: "CH₄ + 2O₂ ==点燃== CO₂ + 2H₂O", en: "CH₄ + 2O₂ ==点燃== CO₂ + 2H₂O" },
          detail: { zh: "天然气主要成分，完全燃烧呈蓝色火焰。", en: "Main component of natural gas; clean blue flame when complete." },
          tags: [{ zh: "燃烧", en: "Combustion" }],
        },
        {
          id: "eq-h2",
          icon: "💧",
          term: { zh: "氢气燃烧", en: "Hydrogen Combustion" },
          oneLiner: { zh: "2H₂ + O₂ ==点燃== 2H₂O", en: "2H₂ + O₂ ==点燃== 2H₂O" },
          tags: [{ zh: "燃烧", en: "Combustion" }],
        },
        {
          id: "eq-neutralize",
          icon: "🧫",
          term: { zh: "盐酸中和氢氧化钠", en: "HCl Neutralizes NaOH" },
          oneLiner: { zh: "HCl + NaOH = NaCl + H₂O", en: "HCl + NaOH = NaCl + H₂O" },
          detail: { zh: "强酸强碱中和，常用酚酞指示终点。", en: "Strong acid-base neutralization; phenolphthalein shows the endpoint." },
          tags: [{ zh: "中和", en: "Neutralization" }],
        },
        {
          id: "eq-na2co3-hcl",
          icon: "🫧",
          term: { zh: "碳酸钠与盐酸", en: "Na₂CO₃ + HCl" },
          oneLiner: { zh: "Na₂CO₃ + 2HCl = 2NaCl + H₂O + CO₂↑", en: "Na₂CO₃ + 2HCl = 2NaCl + H₂O + CO₂↑" },
          detail: { zh: "泡沫灭火器原理之一，产生大量 CO₂。", en: "Underlies foam extinguishers, releasing much CO₂." },
          tags: [{ zh: "复分解", en: "Double" }],
        },
        {
          id: "eq-cao",
          icon: "🧱",
          term: { zh: "生石灰遇水", en: "CaO + Water" },
          oneLiner: { zh: "CaO + H₂O = Ca(OH)₂", en: "CaO + H₂O = Ca(OH)₂" },
          detail: { zh: "剧烈放热，生成熟石灰，用于干燥与建筑。", en: "Highly exothermic, giving slaked lime for drying and building." },
          tags: [{ zh: "化合", en: "Synthesis" }],
        },
        {
          id: "eq-limewater",
          icon: "🥛",
          term: { zh: "二氧化碳使石灰水变浑浊", en: "CO₂ Turns Limewater Cloudy" },
          oneLiner: { zh: "CO₂ + Ca(OH)₂ = CaCO₃↓ + H₂O", en: "CO₂ + Ca(OH)₂ = CaCO₃↓ + H₂O" },
          detail: { zh: "实验室检验 CO₂ 的特征反应；过量 CO₂ 会使沉淀溶解生成 Ca(HCO₃)₂。", en: "The textbook test for CO₂; excess CO₂ redissolves the precipitate." },
          tags: [{ zh: "检验", en: "Test" }],
        },
        {
          id: "eq-rust",
          icon: "🟥",
          term: { zh: "铁生锈（吸氧腐蚀）", en: "Iron Rusting" },
          oneLiner: { zh: "4Fe + 3O₂ + xH₂O = 2Fe₂O₃·xH₂O", en: "4Fe + 3O₂ + xH₂O = 2Fe₂O₃·xH₂O" },
          detail: { zh: "潮湿空气中铁发生电化学腐蚀，生成疏松的红棕色铁锈。", en: "In moist air iron undergoes electrochemical corrosion into flaky rust." },
          tags: [{ zh: "腐蚀", en: "Corrosion" }],
        },
        {
          id: "eq-bacl2",
          icon: "🧂",
          term: { zh: "氯化钡检验硫酸根", en: "Test Sulfate with BaCl₂" },
          oneLiner: { zh: "BaCl₂ + H₂SO₄ = BaSO₄↓ + 2HCl", en: "BaCl₂ + H₂SO₄ = BaSO₄↓ + 2HCl" },
          detail: { zh: "生成不溶于稀硝酸的白色 BaSO₄ 沉淀，用于检验 SO₄²⁻。", en: "White BaSO₄ precipitate insoluble in dilute nitric acid signals SO₄²⁻." },
          tags: [{ zh: "检验", en: "Test" }],
        },
        {
          id: "eq-nahco3",
          icon: "🫧",
          term: { zh: "碳酸氢钠受热分解", en: "NaHCO₃ Decomposition" },
          oneLiner: { zh: "2NaHCO₃ ==△== Na₂CO₃ + H₂O + CO₂↑", en: "2NaHCO₃ ==△== Na₂CO₃ + H₂O + CO₂↑" },
          detail: { zh: "焙制糕点常用作膨松剂，受热放出 CO₂ 使面团疏松。", en: "A leavening agent; heating releases CO₂ that aerates dough." },
          tags: [{ zh: "分解", en: "Decomposition" }],
        },
      ],
    },
    /* ===================== 化学家 ===================== */
    {
      key: "chemists",
      icon: "🧑‍🔬",
      title: { zh: "化学家", en: "Chemists" },
      items: [
        { id: "mendeleev", icon: "📐", term: { zh: "德米特里·门捷列夫", en: "Dmitri Mendeleev" }, oneLiner: { zh: "编制第一张元素周期表，并预言了若干未知元素。", en: "Built the first periodic table and predicted unknown elements." } },
        { id: "lavoisier", icon: "⚖️", term: { zh: "安托万·拉瓦锡", en: "Antoine Lavoisier" }, oneLiner: { zh: "现代化学之父，确立质量守恒与氧化学说。", en: "Father of modern chemistry; conservation of mass and oxygen theory." } },
        { id: "dalton", icon: "⚛️", term: { zh: "约翰·道尔顿", en: "John Dalton" }, oneLiner: { zh: "提出原子论，认为物质由不可再分的原子构成。", en: "Proposed atomic theory: matter is made of indivisible atoms." } },
        { id: "boyle", icon: "🫧", term: { zh: "罗伯特·玻意耳", en: "Robert Boyle" }, oneLiner: { zh: "玻意耳定律（pV = 常量）奠定气体研究基础。", en: "Boyle's law (pV = const) founded the study of gases." } },
        { id: "curie", icon: "☢️", term: { zh: "玛丽·居里", en: "Marie Curie" }, oneLiner: { zh: "发现钋与镭，放射性研究的先驱。", en: "Discovered polonium and radium; pioneer of radioactivity." } },
        { id: "pauling", icon: "🔗", term: { zh: "莱纳斯·鲍林", en: "Linus Pauling" }, oneLiner: { zh: "化学键本质与电负性研究的巨擘，两获诺贝尔奖。", en: "Giant of chemical bonding and electronegativity; two-time Nobel laureate." } },
        { id: "avogadro", icon: "🧮", term: { zh: "阿莫迪欧·阿伏伽德罗", en: "Amedeo Avogadro" }, oneLiner: { zh: "提出同温同压下等体积气体含等量分子（阿伏伽德罗定律）。", en: "Equal gas volumes hold equal molecule counts at same T and P." } },
        { id: "lechatelier", icon: "⚖️", term: { zh: "亨利·勒夏特列", en: "Henry Le Chatelier" }, oneLiner: { zh: "提出平衡移动原理，指导化工生产条件优化。", en: "Stated the equilibrium-shift principle guiding chemical industry." } },
      ],
    },
    /* ===================== 名词词典 ===================== */
    {
      key: "glossary",
      icon: "📖",
      title: { zh: "名词词典", en: "Glossary" },
      items: [
        { id: "mole", icon: "🧮", term: { zh: "摩尔", en: "Mole" }, oneLiner: { zh: "物质的量单位，1 摩尔含阿伏伽德罗常数个基本单元。", en: "Unit of amount of substance; one mole holds Avogadro's number of entities." } },
        { id: "catalyst", icon: "⚡", term: { zh: "催化剂", en: "Catalyst" }, oneLiner: { zh: "改变反应速率却不在反应中消耗的物种。", en: "A species that changes rate without being consumed." } },
        { id: "ph", icon: "🧫", term: { zh: "pH", en: "pH" }, oneLiner: { zh: "氢离子浓度的负对数，衡量溶液酸碱强弱。", en: "Negative log of hydrogen ion concentration; measures acidity." } },
        { id: "isotope", icon: "♒", term: { zh: "同位素", en: "Isotope" }, oneLiner: { zh: "质子数相同、中子数不同的同种元素变体。", en: "Variants of an element with same protons, different neutrons." } },
        { id: "electrolyte", icon: "🔌", term: { zh: "电解质", en: "Electrolyte" }, oneLiner: { zh: "溶于水或熔融后能导电的化合物。", en: "A compound that conducts electricity when dissolved or molten." } },
        { id: "valence", icon: "🔢", term: { zh: "化合价", en: "Valence" }, oneLiner: { zh: "元素原子形成化学键时表现的结合能力，常用数值表示。", en: "An atom's combining capacity, expressed as a number." } },
        { id: "allotrope", icon: "💎", term: { zh: "同素异形体", en: "Allotrope" }, oneLiner: { zh: "同种元素组成的不同单质，如金刚石与石墨。", en: "Different forms of the same element, e.g. diamond and graphite." } },
        { id: "solubility", icon: "💧", term: { zh: "溶解度", en: "Solubility" }, oneLiner: { zh: "一定温度、压强下某物质在溶剂中达到饱和时的浓度。", en: "Concentration at saturation under given T and P." } },
        { id: "activation", icon: "🚀", term: { zh: "活化能", en: "Activation Energy" }, oneLiner: { zh: "反应物变为活化络合物所需的最低能量壁垒。", en: "The energy barrier reactants must cross to react." } },
        { id: "oxidation-state", icon: "🔋", term: { zh: "氧化数", en: "Oxidation State" }, oneLiner: { zh: "人为规定的原子表观电荷数，用于判断氧化还原。", en: "An assigned apparent charge used to track redox." } },
      ],
    },
  ],
  refs: [
    { label: { zh: "Khan Academy · 化学", en: "Khan Academy · Chemistry" }, url: "https://www.khanacademy.org/science/chemistry", type: { zh: "科普", en: "Educational" } },
    { label: { zh: "PubChem", en: "PubChem" }, url: "https://pubchem.ncbi.nlm.nih.gov/", type: { zh: "工具", en: "Reference" } },
    { label: { zh: "Royal Society of Chemistry", en: "Royal Society of Chemistry" }, url: "https://www.rsc.org/", type: { zh: "机构", en: "Institution" } },
    { label: { zh: "Wikipedia · Chemistry", en: "Wikipedia · Chemistry" }, url: "https://en.wikipedia.org/wiki/Chemistry", type: { zh: "百科", en: "Encyclopedia" } },
  ],
};
